version: '3.9'

services:
  db:
    image: postgres:15
    container_name: kidora-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-kidora}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
